### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by Thunderducky** [kmamal/node-sdl#41]
I tried running the base examples with [bun](https://bun.sh/) and got segmentation errors when calling `window.render`.
I suspect it's related to differences in how the buffer is handled.

If there is a way around this/workaround that'd be great!

**Comment by kmamal** [comment]
@Thunderducky I'd like to support bun eventually, but right now their support for napi modules is not even finished (https://github.com/oven-sh/bun/issues/158) and I am encountering too many weird bugs when trying to run the examples. I'd suggest leaving the issue open and I'll revisit it as bun becomes more stable in the future.

**Comment by Thunderducky** [comment]
Thank you! Love the library

**Comment by pedroth** [comment]
I could run a small example with `bun`

```js
// index.js
import sdl from '@kmamal/sdl'

// Setup
const window = sdl.video.createWindow({ title: "Canvas" })
window.setFullscreen(true);
const { pixelWidth: width, pixelHeight: height } = window
const buffer = Buffer.alloc(width * height * 4).fill(0);
for (let n = 0; n < buffer.length; n += 4) {
    const i = Math.floor(n / (4 * width));
    const j = Math.floor((n / 4) % width);
    const x = j;
    const y = height - 1 - i;
    buffer[n] = Math.min(255, (x / width) * 255);
    buffer[n + 1] = Math.min(255, (y / height) * 255);
    buffer[n + 2] = 0;
    buffer[n + 3] = 255;
}
console.log("debug ", buffer)
window.render(width, height, width * 4, 'rgba32', buffer);
```

Then ran `bun index.js`, with `bun` version `1.0.28`.


Great lib btw, thank you @kmamal

**Comment by pedroth** [comment]
I could run a small example with `bun`

```js
// index.js
import sdl from '@kmamal/sdl'

// Setup
const window = sdl.video.createWindow({ title: "Canvas" })
window.setFullscreen(true);
const { pixelWidth: width, pixelHeight: height } = window
const buffer = Buffer.alloc(width * height * 4).fill(0);
for (let n = 0; n < buffer.length; n += 4) {
    const i = Math.floor(n / (4 * width));
    const j = Math.floor((n / 4) % width);
    const x = j;
    const y = height - 1 - i;
    buffer[n] = Math.min(255, (x / width) * 255);
    buffer[n + 1] = Math.min(255, (y / height) * 255);
    buffer[n + 2] = 0;
    buffer[n + 3] = 255;
}
console.log("debug ", buffer)
window.render(width, height, width * 4, 'rgba32', buffer);
```

Then ran `bun index.js`, with `bun` version `1.0.28`.


Great lib btw, thank you @kmamal

**Comment by pedroth** [comment]
Just a note here about using `bun` to install `node-sdl`:

https://github.com/oven-sh/bun/issues/9220

One needs to add `node-sdl` as a `trustedDependencies`, for bun to install.

@Thunderducky @kmamal

**Comment by kmamal** [comment]
Linking this issue so I can track it easier: https://github.com/oven-sh/bun/issues/9743

**Comment by rafaellehmkuhl** [comment]
I'm still having a hard time making it work with bun. I'm receiving the following:

```
build started... (x2)
✓ 1 modules transformed.
dist/electron/preload.js  1.85 kB │ gzip: 0.53 kB
built in 80ms.
✓ 14 modules transformed.
[commonjs--resolver] node_modules/@kmamal/sdl/dist/sdl.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
file: .../cockpit/node_modules/@kmamal/sdl/src/javascript/audio/audio-playback-instance.js:1:0
1: ����
      � ��h__TEXT��
   ^
2: __text__TEXT�&���&�__stubs__TEXT...
3: H�
     __stub_helper__TEXT��D
.../cockpit/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
          ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (.../cockpit/node_modules/electron/index.js:17:11)
    at Object.<anonymous> (.../cockpit/node_modules/electron/index.js:21:18)
```

An tip around that would be very appreciated. The reproducible repository/commit is [here](https://github.com/rafaellehmkuhl/cockpit-public/tree/hid-for-electron-joysticks-sdl).

**Comment by kmamal** [comment]
@rafaellehmkuhl Are you sure that error is specific to bun? It doesn't happen with Nodejs?

It looks to me that you are trying to include the @kmamal/sdl package in some sort of bundle (probably via rollup or electron-packager?) and your bundler is complaining because sdl.node is a binary file it doesn't know how to handle. You should probably look into the "Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)" error.

**Comment by rafaellehmkuhl** [comment]
> [@rafaellehmkuhl](https://github.com/rafaellehmkuhl) Are you sure that error is specific to bun? It doesn't happen with Nodejs?
> 
> It looks to me that you are trying to include the @kmamal/sdl package in some sort of bundle (probably via rollup or electron-packager?) and your bundler is complaining because sdl.node is a binary file it doesn't know how to handle. You should probably look into the "Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)" error.

Hey @kmamal, thanks for the reply!

I actually tried several things and but in the end it it a problem with Bun indeed.

I have removed every configuration and reinstalled everything with Yarn. It's working like a charm. You can see it [here](https://github.com/rafaellehmkuhl/cockpit-public/tree/sdl-clear-test-with-yarn).

The "/sdl.node (1:0): Unexpected character" problem was being caused by how I was importing the library, but it was actually not affecting the usage. The real problem was the "Electron failed to install correctly" one.

**Comment by Kasparsu** [comment]
As of right now I can run examples with bun no problem. But there seems to be an issue when I try to compile it with bun build --compile that it runs into. And I would expect that to be the desired feature for would be developer since bun offers a neat way to package code into single executable.

**Comment by rafaellehmkuhl** [comment]
> As of right now I can run examples with bun no problem. But there seems to be an issue when I try to compile it with bun build --compile that it runs into. And I would expect that to be the desired feature for would be developer since bun offers a neat way to package code into single executable.

I think the problem I'm facing is actually about using `node-sdl` with Bun+Electron, not just Bun. Or maybe just Electron? I didn't test the lib alone with Electron.

**Comment by Kasparsu** [comment]
@rafaellehmkuhl I feel like there is something going on with your configs instead it is trying to parse .node file as a js file and that causes the issue.

**Comment by rafaellehmkuhl** [comment]
> [@rafaellehmkuhl](https://github.com/rafaellehmkuhl) I feel like there is something going on with your configs instead it is trying to parse .node file as a js file and that causes the issue.

I explained it better on #73, but basically `electron-builder` was trying to rebuild the binaries. It was a matter of forcing it to skip.
