### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by notcl4y14** [kmamal/node-sdl#53]
```js
import sdl from '@kmamal/sdl'
import createContext from '@kmamal/gl'
```

```
node:internal/modules/cjs/loader:1473
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Sev\Desktop\Projects\nodesdl-game\node_modules\@kmamal\gl\build\Release\webgl.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (C:\Users\Sev\Desktop\Projects\nodesdl-game\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\Sev\Desktop\Projects\nodesdl-game\node_modules\@kmamal\gl\src\javascript\native-gl.js:1:40)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by SupertigerDev** [comment]
I found a way.

go to this folder `node_modules\@kmamal\gl `

run `npm run build`
you will need to have all the build tools ready

**Comment by kmamal** [comment]
This should be fixed in the latest version.
